#!/usr/bin/python
from __future__ import (absolute_import, division, print_function, unicode_literals)
import collections
import sys
import cmd

if __name__ == '__main__':
    ct = collections.Counter()

    for term in sys.argv:
        for filename in cmd.ack(term):
            ct[filename] += 1

    for filename, terms_appeared in ct.items():
        if terms_appeared == len(sys.argv) - 1:
            print(filename)
