#!/usr/bin/python
from __future__ import (absolute_import, division, print_function, unicode_literals)
import collections
import sys
import cmd

if __name__ == '__main__':
    files = set(cmd.ack(sys.argv[1]))

    for term in sys.argv[2:]:
        for filename in cmd.ack(term):
            files.discard(filename)

    for filename in sorted(files):
        print(filename)
