#!/usr/bin/perl -w
use strict;
use Getopt::Long;
GetOptions (
    'i|ignore-case' => \my $ignorecase
);

my $feature      = $ignorecase ? "iname" : "name";
my $search_param = join("*", @ARGV);

my $filter_rc = `find_up .fnrc`;
chomp $filter_rc;
my $cmd = qq/find -L "`pwd -P`" -$feature "*$search_param*" | egrep -vf "$filter_rc"/;
system($cmd);
