#!/usr/bin/perl -w
use strict;
use Getopt::Long;
GetOptions (
    'i|ignore-case' => \my $ignorecase
);

my $feature      = $ignorecase ? "iname" : "name";
my $search_param = join("*", @ARGV);

my $cmd = qq/find -L "`pwd -P`" -$feature "*$search_param*" | grep -v '\/target\/' | grep -v '.svn' | grep -v '.hg' | grep -v swp | grep -v swo | grep -v pyc | grep -v class | grep -v __init__.py /;
system($cmd);
